//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by MVComms.rc
//
#define IDS_COMMS_ERROR_NO_ERROR        101
#define IDS_COMMS_ERROR_OPEN            102
#define IDS_COMMS_ERROR_SEND            103
#define IDS_COMMS_ERROR_SEND_CLOSED     104
#define IDS_COMMS_ERROR_RECV            105
#define IDS_COMMS_ERROR_RECV_CLOSED     106
#define IDS_COMMS_ERROR_CLOSE           107
#define IDS_COMMS_ERROR_CLEAR_ERROR     108
#define IDS_COMMS_ERROR_END_POINT_INVALID 109
#define IDS_COMMS_ERROR_CONFIGURE       110
#define IDS_COMMS_ERROR_INIT            111
#define IDS_COMMS_ERROR_DEINIT          112
#define IDS_COMMS_ERROR_RECV_TIMEOUT    113
#define IDS_COMMS_ERROR_SEND_TIMEOUT    114
#define IDS_COMMS_ERROR_END_POINT_GET   115
#define IDS_COMMS_ERROR_SERVER_START    116
#define IDS_COMMS_ERROR_SERVER_LISTEN   117
#define IDS_COMMS_ERROR_SERVER_STOP     118
#define IDS_COMMS_ERROR_RECV_END        119
#define IDS_COMMS_ERROR_RECV_BLOCK      120
#define IDS_COMMS_ERROR_RECV_COUNT      121
#define IDS_COMMS_ERROR_CONNECT_TIMEOUT 122
#define IDS_COMMS_ERROR_SEND_END        123
#define IDS_COMMS_ERROR_PARAM_INVALID   124
#define IDS_COMMS_ERROR_CONNECTION_BUSY 125
#define IDS_COMMS_ERROR_INVALID_OPERATION 126

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        126
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1001
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
