//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by PCMOVA.rc
//
#define IDS_PCMOVA_ERROR_NO_ERROR       101
#define IDS_PCMOVA_ERROR_ASSERTION_FAILURE 102
#define IDS_PCMOVA_ERROR_ALREADY_INIT   103
#define IDS_PCMOVA_ERROR_OUT_OF_MEMORY  104
#define IDS_PCMOVA_ERROR_PARAM_INVALID  105
#define IDS_PCMOVA_ERROR_DATASET_OPEN   106
#define IDS_PCMOVA_ERROR_DATASET_READ   107
#define IDS_PCMOVA_ERROR_DATASET_FORMAT 108
#define IDS_PCMOVA_ERROR_DATASET_CLOSE  109
#define IDS_PCMOVA_ERROR_TASK_INIT      110
#define IDS_PCMOVA_ERROR_TASK_DEINIT    111
#define IDS_PCMOVA_ERROR_TERMINATE      112
#define IDS_PCMOVA_ERROR_HANDSHAKE      113
#define IDS_PCMOVA_ERROR_INITIALISE     114
#define IDS_PCMOVA_ERROR_UPDATE         115
#define IDS_PCMOVA_ERROR_CONTROLLER_SEND 116
#define IDS_PCMOVA_ERROR_CONTROLLER_RECEIVE 117
#define IDS_PCMOVA_ERROR_USER_SEND      118
#define IDS_PCMOVA_ERROR_USER_RECEIVE   119
#define IDS_PCMOVA_ERROR_MSG_CHECKSUM   120
#define IDS_PCMOVA_ERROR_MSG_LENGTH     121
#define IDS_PCMOVA_ERROR_MSG_START      122
#define IDS_PCMOVA_ERROR_MSG_ID         123
#define IDS_PCMOVA_ERROR_MSG_TYPE       124
#define IDS_PCMOVA_ERROR_MSG_DATA       125
#define IDS_PCMOVA_ERROR_TIME           126
#define IDS_PCMOVA_ERROR_CONTROLLER_INIT 127
#define IDS_PCMOVA_ERROR_CONTROLLER_DEINIT 128
#define IDS_PCMOVA_ERROR_USER_INIT      129
#define IDS_PCMOVA_ERROR_USER_DEINIT    130
#define IDS_PCMOVA_ERROR_NOT_INITwew    131
#define IDS_PCMOVA_ERROR_NOT_INIT       131
#define IDS_PCMOVA_ERROR_DATASET_VERSION 132
#define IDS_PCMOVA_ERROR_DATASET_CHECKSUM 133
#define IDS_KERNEL_ERROR_NO_ERROR       134
#define IDS_KERNEL_ERROR_MOVA_BACK_ON_LINE 135
#define IDS_KERNEL_ERROR_FAULTY_DETECTOR 136
#define IDS_KERNEL_ERROR_STAGE_NOT_ENDED 137
#define IDS_KERNEL_ERROR_INTERGREEN_NOT_ENDED 138
#define IDS_KERNEL_ERROR_INVALID_STAGE_DEMANDED 139
#define IDS_KERNEL_ERROR_WRONG_STAGE_CONFIRMED 140
#define IDS_KERNEL_ERROR_STAGE_STUCK_ON 141
#define IDS_KERNEL_ERROR_WATCHDOG_ROUTINE 142
#define IDS_KERNEL_ERROR_CONTROLLER_READY_BIT_OFF 143
#define IDS_KERNEL_ERROR_CONTROLLER_READY_BIT_ON 144
#define IDS_KERNEL_ERROR_PROGRAM_ERROR  145
#define IDS_KERNEL_ERROR_CHECKSUM_ERROR 146
#define IDS_KERNEL_ERROR_RELOADING_ERROR 147
#define IDS_KERNEL_ERROR_MULTIPLE_STAGE_CONFIRMS 148
#define IDS_KERNEL_ERROR_MOVA_RESTARTED 149
#define IDS_KERNEL_ERROR_DIVIDE_ERROR   150
#define IDS_KERNEL_ERROR_EMPTY_REPOSITORY_AREA 151
#define IDS_KERNEL_ERROR_REPOSITORY_CHECKSUM 152
#define IDS_KERNEL_ERROR_DEFAULT_LOADED 153
#define IDS_PCMOVA_ERROR_KERNEL_FATAL   154
#define IDS_PCMOVA_ERROR_KERNEL_USER_FATAL 155
#define IDS_PCMOVA_ERROR_TASK_SUSPEND   156
#define IDS_PCMOVA_ERROR_TASK_RESUME    157

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        158
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1001
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
